/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author LAB-USR-CHIM-A0208
 */
public class VistaFormulario extends javax.swing.JFrame {

    /**
     * Creates new form VistaFormulario
     */
    public VistaFormulario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombreAlumno = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lblPregunta1 = new javax.swing.JLabel();
        alter1_1 = new javax.swing.JRadioButton();
        alter1_2 = new javax.swing.JRadioButton();
        alter1_3 = new javax.swing.JRadioButton();
        alter1_4 = new javax.swing.JRadioButton();
        lblPregunta3 = new javax.swing.JLabel();
        alter2_1 = new javax.swing.JRadioButton();
        alter2_2 = new javax.swing.JRadioButton();
        alter2_3 = new javax.swing.JRadioButton();
        alter2_4 = new javax.swing.JRadioButton();
        lblPregunta2 = new javax.swing.JLabel();
        alter3_1 = new javax.swing.JRadioButton();
        alter3_2 = new javax.swing.JRadioButton();
        alter3_3 = new javax.swing.JRadioButton();
        alter3_4 = new javax.swing.JRadioButton();
        btnSiguente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Alumno:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("ENCUESTA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1)
                        .addGap(29, 29, 29)
                        .addComponent(txtNombreAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombreAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));

        lblPregunta1.setText("Pregunta 1");

        alter1_1.setBackground(new java.awt.Color(204, 255, 204));
        buttonGroup1.add(alter1_1);
        alter1_1.setText("...");
        alter1_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alter1_1ActionPerformed(evt);
            }
        });

        alter1_2.setBackground(new java.awt.Color(204, 255, 204));
        buttonGroup1.add(alter1_2);
        alter1_2.setText("...");

        alter1_3.setBackground(new java.awt.Color(204, 255, 204));
        buttonGroup1.add(alter1_3);
        alter1_3.setText("...");

        alter1_4.setBackground(new java.awt.Color(204, 255, 204));
        buttonGroup1.add(alter1_4);
        alter1_4.setText("...");

        lblPregunta3.setText("Pregunta 3");

        alter2_1.setBackground(new java.awt.Color(204, 255, 204));
        buttonGroup2.add(alter2_1);
        alter2_1.setText("...");

        alter2_2.setBackground(new java.awt.Color(204, 255, 204));
        buttonGroup2.add(alter2_2);
        alter2_2.setText("...");
        alter2_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alter2_2ActionPerformed(evt);
            }
        });

        alter2_3.setBackground(new java.awt.Color(204, 255, 204));
        buttonGroup2.add(alter2_3);
        alter2_3.setText("...");

        alter2_4.setBackground(new java.awt.Color(204, 255, 204));
        buttonGroup2.add(alter2_4);
        alter2_4.setText("...");

        lblPregunta2.setText("Pregunta 2");

        alter3_1.setBackground(new java.awt.Color(204, 255, 204));
        buttonGroup3.add(alter3_1);
        alter3_1.setText("...");

        alter3_2.setBackground(new java.awt.Color(204, 255, 204));
        buttonGroup3.add(alter3_2);
        alter3_2.setText("...");

        alter3_3.setBackground(new java.awt.Color(204, 255, 204));
        buttonGroup3.add(alter3_3);
        alter3_3.setText("...");

        alter3_4.setBackground(new java.awt.Color(204, 255, 204));
        buttonGroup3.add(alter3_4);
        alter3_4.setText("...");

        btnSiguente.setText("Siguiente");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSiguente)
                .addGap(24, 24, 24))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPregunta2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(alter2_1)
                        .addGap(52, 52, 52)
                        .addComponent(alter2_2)
                        .addGap(39, 39, 39)
                        .addComponent(alter2_3)
                        .addGap(32, 32, 32)
                        .addComponent(alter2_4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(alter1_1)
                        .addGap(33, 33, 33)
                        .addComponent(alter1_2)
                        .addGap(43, 43, 43)
                        .addComponent(alter1_3)
                        .addGap(39, 39, 39)
                        .addComponent(alter1_4))
                    .addComponent(lblPregunta1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(alter3_1)
                                .addGap(43, 43, 43)
                                .addComponent(alter3_2)
                                .addGap(52, 52, 52)
                                .addComponent(alter3_3))
                            .addComponent(lblPregunta3))
                        .addGap(32, 32, 32)
                        .addComponent(alter3_4)))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblPregunta1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alter1_1)
                    .addComponent(alter1_2)
                    .addComponent(alter1_3)
                    .addComponent(alter1_4))
                .addGap(24, 24, 24)
                .addComponent(lblPregunta2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alter2_1)
                    .addComponent(alter2_2)
                    .addComponent(alter2_3)
                    .addComponent(alter2_4))
                .addGap(18, 18, 18)
                .addComponent(lblPregunta3)
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alter3_2)
                    .addComponent(alter3_1)
                    .addComponent(alter3_3)
                    .addComponent(alter3_4))
                .addGap(30, 30, 30)
                .addComponent(btnSiguente)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alter2_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alter2_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alter2_2ActionPerformed

    private void alter1_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alter1_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alter1_1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaFormulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JRadioButton alter1_1;
    public javax.swing.JRadioButton alter1_2;
    public javax.swing.JRadioButton alter1_3;
    public javax.swing.JRadioButton alter1_4;
    public javax.swing.JRadioButton alter2_1;
    public javax.swing.JRadioButton alter2_2;
    public javax.swing.JRadioButton alter2_3;
    public javax.swing.JRadioButton alter2_4;
    public javax.swing.JRadioButton alter3_1;
    public javax.swing.JRadioButton alter3_2;
    public javax.swing.JRadioButton alter3_3;
    public javax.swing.JRadioButton alter3_4;
    public javax.swing.JButton btnSiguente;
    public javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.ButtonGroup buttonGroup2;
    public javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JLabel lblPregunta1;
    public javax.swing.JLabel lblPregunta2;
    public javax.swing.JLabel lblPregunta3;
    public javax.swing.JTextField txtNombreAlumno;
    // End of variables declaration//GEN-END:variables
}
